### DISCUSSION TITLE
TTP Group and Complience test "Bug"

### DISCUSSION THREAD

**Discussion by aascedu** [amyasnikov/validity#125] [Q&A] [answered]
Hello,

I just started making serializer and tests for my organization.

Here is what I discovered and wished to know if it was normal or not.
Before I used to name my groups in the TTP parser with dash ('-') like 'line-vty' or 'no-ip' but I discovered it is causing problems when running Tests so I changed to 'linevty' or 'noip'. I'll show you the errors I get with dash-containing group name.

First, without a dash : here is a part of my Serialized state for a router device.
```
linevty:
- mode: ssh
  mode2: /
  range: 0 4
- mode: ssh
  mode2: /
  range: 5 15
```

I wanted to check that none of the mode had "telnet" in them. So I came up with this test.
`not jq.all('.linevty[] | select(.mode == "telnet" or .mode2 == "telnet").range', device.config)`

Here is the output : 
![image](https://github.com/user-attachments/assets/5c5bc741-41e0-4fa0-b3ef-18dc4166f7a9)

Now, when I change 'linevty' to 'line-vty' : 
the Serialized state 
```
line-vty:
- mode: ssh
  mode2: /
  range: 0 4
- mode: ssh
  mode2: /
  range: 5 15
```
(still looks the same)

The test doesn't change except for the name of 'linevty' to 'line-vty' : 
`not jq.all('.line-vty[] | select(.mode == "telnet" or .mode2 == "telnet").range', device.config)`

Now the output is like that : 
![image](https://github.com/user-attachments/assets/127d2463-3a42-4e6d-88aa-cf30559d7600)

Since, it is a jq error, it might not be the right place to discuss, but I thought someone here would be aware of that problem when using JQ to produce tests quite frequently.

Thank you for your help ;)
Arthur
