### DISCUSSION TITLE
User Netbox config to Validity

### DISCUSSION THREAD

**Discussion by rsp1991** [amyasnikov/validity#83] [General]
Hello everyone,

I'd like to user my settings (hostname, description, vlan, etc) did in Netbox to compliance, example:

device created with name SW-01, interface 0/1 with description "UPLINK"

**Comment by amyasnikov** [comment]
You may use all device properties inside test expression (e.g. `device.interfaces.all()` gives you access to all interfaces provisioned inside NetBox for a particular device).
Usually to compose a new test you first have to decide which properties you're going to compare with each other (e.g. compare **interface descriptions** inside NetBox and those ones configured on a device).

**Reply by rsp1991** [reply]
Hi @amyasnikov 

Do you have any example with compare the descriptions?

**Reply by amyasnikov** [reply]
Something like this:
```python
{iface.name: iface.description for iface in device.interfaces.all()} == \
{iface['name']: iface['description'] for iface in device.config['interfaces']}
```

It supposes you have serialized configuration like this(yaml):
```yaml
interfaces:
- name: ge-0/0/1
  description: my_awesome_interface
...
```

**Reply by rsp1991** [reply]
I tried your advice but after I run the script I see the wrong below:

![image](https://github.com/amyasnikov/validity/assets/119420171/49205106-5c7b-4ee3-b08c-67c9fdc2f0cb)

My serialized is similar to your example:

```
interfaces:
- description: '## UPLINK ##'
  interface: Port-channel1
  switchport_mode: trunk
```

I did some changes to work in my environment

```
{iface.name: iface.description for iface in device.interfaces.all()} == \
{iface['interface']: iface['description'] for iface in device.state.show_running_interface['interfaces']}
```
