### ISSUE TITLE
Random failed tests on routeros devices

### ISSUE THREAD

**Issue by hart323** [amyasnikov/validity#121]
### Validity Version

3.0.3

### NetBox Version

4.1.1

### Python Version

3.12.3

### Steps to Reproduce

As amount of tests for routeros and number of routeros devices started to increase (8 tests/33 devices as of now) I noticed that I get random failed tests. For example if I run 8 tests/1 device I get result with all tests passed, but if I run 8 tests/33 devices I end up with around 80% of tests passed but others failed. 
This is how particular test for particular device may look when scheduled 8/33 tests have been done:
![изображение](https://github.com/user-attachments/assets/0c000547-e31e-4ba8-94cd-fc90f29e12fb)

It seems like failed tests are because of netmiko or validity collecting results from netmiko because command result file may contain the following lines:
```
POLLING ERROR
AssertionError: 
```
or trimmed output like:
```
             enabled: yes
         primary-ntp: 10.10.10.10
       secondary-ntp: 10.10.10.11
    server-dns-names: 
                mode: unicast
       poll-interval: 15m
       active-server: 10.10.10.10
    last-update-from: 10.10.10.10
  las
```
or some other strange lines which looks like lines from mikrotik config but not related to command sent to device. I attach this example when I find one.

I added to routeros poller config line: ```session_log: /tmp/netmiko_session.log``` and this log file contains all command outputs from device however device result file does not contain data.

Note. I don't notice same behavior on cisco.ios devices.

### Traceback

```shell
No tracebacks
```
